In [ ]:
#PyTorch use tensors to encode 
#inputs, outputs and parameters of models
#Tensor can run on GPUs and other hardware accelerators.


In [1]:
import torch
import numpy as np

In [2]:
#Initializing a Tensor with exist

#from data directly
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
#from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
#from another tensor
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(f"Direct Tensor:\n{x_data}\n")
print(f"Numpy Tensor:\n{x_np}\n")
print(f"Ones Tensor:\n{x_ones}\n")
print(f"Random Tensor:\n{x_rand}\n")

Direct Tensor:
tensor([[1, 2],
        [3, 4]])

Numpy Tensor:
tensor([[1, 2],
        [3, 4]])

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.2628, 0.7452],
        [0.9777, 0.6908]])



In [9]:
#Initializing a Tensor with shape
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zeros Tensor:\n{zeros_tensor}\n")

Random Tensor:
tensor([[0.9141, 0.0608, 0.0386],
        [0.9358, 0.4678, 0.6984]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [2]:
#Attributes of a Tensor
#Attritutes: shape, datatype, device on which they are stored
tensor = torch.rand(3,4)

print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype of tensor:{tensor.dtype}")
print(f"Device tensor is stored on:{tensor.device}")

Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu


In [3]:
#Operation on Tensors

#Move tensor to another device.
#Note:Copying large tensors across devices
#can be expensive in terms of time and memory
if torch.cuda.is_available():
    print("Tensor is being moved to cuda..")
    tensor = tensor.to('cuda')
    print("Done!")


Tensor is being moved to cuda..
Done!


In [6]:
#Standard numpy-like indexing and slicing
tensor = torch.ones(4,4)
print('First row',tensor[0])
print('First column',tensor[:,0])
print('Last column',tensor[...,-1])
tensor[:,1]=0
print(tensor)



First row tensor([1., 1., 1., 1.])
First column tensor([1., 1., 1., 1.])
Last column tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [19]:
#Joining tensors. To concatenate a sequence of tensor
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [28]:
#Arithmetic operations

#Matrix multiplication
#T means transposition
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=y3)

#element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

#Single-element tensor: One-element tensor
#e.g. aggregating all values of tensor into one value
#item() is used to convert one-element tensors to python
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item)) 

#In-place operations
#store the result into the operand,use _ after operation
#Dangerous when used in computing derivatives,
#history will get lost
print(tensor, "\n")
tensor.add_(5)
print(tensor)

12.0 <class 'float'>
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [29]:
#Bridge with NumPy

#Tensors on the CPU and NumPy arrays can share their underlying memory locations,
#and changing one will change the other.

#Tensor to NumPy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

#Change synchronously
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

#NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)

#Change synchronously
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
